name: CodeClimate.com

on:
  workflow_call:
    secrets:
      CODE_CLIMATE_REPORT_TOKEN:
        required: true

jobs:
  CodeClimate:
    name: CodeClimate.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: target
          path: ./target/
      - run: ls -R
      - name: Upload to CodeClimate.com
        uses: paambaati/codeclimate-action@v9.0.0
        with:
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORT_TOKEN }}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
