name: Build and Test on Push
on:
  push:
    branches:
      - "*"

jobs:
  build-maven-deb:
    uses: ./.github/workflows/build-maven-deb.yml
  sonarcloud:
    needs: build-maven-deb
    uses: ./.github/workflows/quality-sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  codeclimate:
    needs: build-maven-deb
    uses: ./.github/workflows/quality-codeclimate.yml
    secrets:
      CODE_CLIMATE_REPORT_TOKEN: ${{ secrets.CODE_CLIMATE_REPORT_TOKEN }}
