name: Build and Test on Push
on:
  push:
    branches:
      - "*"
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      CODE_CLIMATE_REPORT_TOKEN:
        required: true

jobs:
  build-maven:
    uses: ./.github/workflows/build-maven.yml
  build-deb:
    needs: build-maven
    uses: ./.github/workflows/build-deb.yml
  build-rpm:
    needs: build-maven
    uses: ./.github/workflows/build-rpm.yml
  sonarcloud:
    needs: [build-maven, build-deb]
    uses: ./.github/workflows/quality-sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  codeclimate:
    needs: [build-maven, build-deb]
    uses: ./.github/workflows/quality-codeclimate.yml
    secrets:
      CODE_CLIMATE_REPORT_TOKEN: ${{ secrets.CODE_CLIMATE_REPORT_TOKEN }}
